Repository thomas7carriere/Project4806, pull requests merged in 2021-04, with the labels that each got.

#64 added dependencies for Jib
  pom.xml
Labels: enhancement

#68 Navigation bar and CSS
  src/main/resources/static/QuestionnaireIcon.png
  src/main/resources/static/index.html
  src/main/resources/static/navBar.html
  src/main/resources/static/numberIcon.png
  src/main/resources/static/returnToMonke.gif
  src/main/resources/static/styles.css
  src/main/resources/templates/createSurvey.html
  src/main/resources/templates/editSurvey.html
  src/main/resources/templates/helpPage.html
  src/main/resources/templates/mySurveys.html
  src/main/resources/templates/viewResult.html
  src/main/resources/templates/viewSurvey.html
  src/main/resources/templates/viewSurveyList.html
Labels: enhancement

#69 Added Back buttons #61
  src/main/resources/static/scripts/mySurveys.js
  src/main/resources/templates/createSurvey.html
  src/main/resources/templates/editSurvey.html
  src/main/resources/templates/helpPage.html
  src/main/resources/templates/mySurveys.html
  src/main/resources/templates/viewResult.html
  src/main/resources/templates/viewSurvey.html
  src/main/resources/templates/viewSurveyList.html
Labels: enhancement

#75 fixed edit error
  src/main/java/application/controllers/MySurveysController.java
  src/main/resources/static/scripts/editSurvey.js
  src/main/resources/templates/editSurvey.html
Labels: bug

#77 Fixed formatting issue with html
  src/main/resources/static/index.html
  src/main/resources/static/navBar.html
Labels: documentation

#70 Added error pages
  src/main/resources/application.properties
  src/main/resources/templates/error.html
  src/main/resources/templates/error/403.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/500.html
Labels: enhancement

#71 Add Lombok support
  .gitignore
  pom.xml
  src/main/java/application/controllers/MySurveysController.java
  src/main/java/application/controllers/SurveyController.java
  src/main/java/application/models/AnswerDTO.java
  src/main/java/application/models/EditDTO.java
  src/main/java/application/models/MultipleChoiceQuestion.java
  src/main/java/application/models/OpenEndedQuestion.java
  src/main/java/application/models/Question.java
  src/main/java/application/models/QuestionDTO.java
  src/main/java/application/models/RangeQuestion.java
  src/main/java/application/models/ResultDTO.java
  src/main/java/application/models/Survey.java
  src/main/java/application/models/dto/AnswerDTO.java
  src/main/java/application/models/dto/EditDTO.java
  src/main/java/application/models/dto/QuestionDTO.java
  src/main/java/application/models/dto/ResultDTO.java
  src/main/java/application/models/dto/SurveyDTO.java
  src/main/resources/templates/viewResult.html
  src/main/resources/templates/viewSurvey.html
  src/test/java/application/controllers/TestMySurveysController.java
  src/test/java/application/controllers/TestSurveyController.java
  src/test/java/application/models/TestMultipleChoiceQuestion.java
  src/test/java/application/models/TestRangeQuestion.java
  src/test/java/application/models/dto/TestAnswerDTO.java
  src/test/java/application/models/dto/TestEditDTO.java
  src/test/java/application/models/dto/TestQuestionDTO.java
  src/test/java/application/models/dto/TestResultDTO.java
  src/test/java/application/models/dto/TestSurveyDTO.java
Labels: enhancement

#79 Added better test
  src/test/java/application/controllers/TestMySurveysController.java
Labels: test

#81 updated the readMe and documents for Milestone3
  Documents/UML-Milstone3.png
  README.md
Labels: documentation
